version: '3.9'
services:
  web:
    build: .
    ports:
      - '80:4001'
    volumes:
      - .:/code
    environment:
      PORT: 4001
  db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
